version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    restart: unless-stopped
    ports:
      - 33200:5055/tcp
    volumes:
      - /opt/overseerr:/app/config:rw
    environment:
      - TZ=America/New_York
      # - LOG_LEVEL=debug