version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    ports:
      - 25100:9696/tcp
    volumes:
      - /opt/prowlarr:/config:rw
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}