version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  pmm:
    container_name: pmm
    image: meisnate12/plex-meta-manager
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - UID=$PUID
      - GID=$PGID
      - PMM_TIME=6:00
    volumes:
      - $APPDATA/pmm:/config:rw
    security_opt:
      - no-new-privileges:true