version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_COMMUNITY_THEME=true
      - TP_THEME=trueblack
    ports:
      - 25100:9696/tcp
    volumes:
      - $APPDATA/prowlarr:/config:rw
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:9696 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3