version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

x-environment: &default-environment
  environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID
    - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
    - TP_COMMUNITY_THEME=true
    - TP_THEME=trueblack

x-settings: &settings
  image: lscr.io/linuxserver/radarr
  restart: unless-stopped  
  security_opt:
    - no-new-privileges:true
  healthcheck:
    test: "curl --fail http://localhost:7878 || exit 1"
    interval: 1m30s
    timeout: 10s
    retries: 2

services:
  radarr1080p:
    container_name: radarr1080p
    ports:
      - 26200:7878/tcp
    volumes:
      - $MEDIADIR/movies:/mnt/media/movies:rw,slave
      - $APPDATA/radarr1080p:/config:rw
    <<: [*default-environment, *settings]
  radarr4k:
    container_name: radarr4k
    ports:
      - 26201:7878/tcp
    volumes:
      - $MEDIADIR/movies:/mnt/media/movies:rw,slave
      - $APPDATA/radarr4k:/config:rw
    <<: [*default-environment, *settings]
  radarranime:
    container_name: radarranime
    ports:
      - 26202:7878/tcp
    volumes:
      - $MEDIADIR/movies:/mnt/media/movies:rw,slave
      - $APPDATA/radarranime:/config:rw
    <<: [*default-environment, *settings]