version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    environment:
      - TZ=$TZ
    volumes:
      - $APPDATA/recyclarr:/config:rw
    security_opt:
      - no-new-privileges:true
    user: $PUID:$PGID