# docker network create -d bridge uptime-kuma
version: '3.3'

networks:
  default:
    external: true
    name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $APPDATA/uptime-kuma:/app/data
    ports:
      - 33001:3001
    environment:
      - TZ=$TZ
    healthcheck:
      test: ['CMD', 'node', 'extra/healthcheck.js']
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 180s