version: "3.6"
services:
  pihole:
    cap_add:
      - NET_ADMIN
    container_name: pihole
    entrypoint:
      - /s6-init
    environment:
      - TZ=Europe/London
      - INTERFACE=br0
      - DNSMASQ_LISTENING=all
      - PIHOLE_DNS_=8.8.8.8;8.8.4.4
      - ServerIP=192.168.0.6
      - ServerIPv6=
      - WEBUIBOXEDLAYOUT=boxed
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Serenity-Unraid
      - HOST_CONTAINERNAME=pihole
      - UDP_PORT_67=67
      - WEBPASSWORD=admin
      - IPv6=False
      - TCP_PORT_53=53
      - UDP_PORT_53=53
      - TCP_PORT_80=80
      - TCP_PORT_443=443
      - PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - phpver=php
      - PIHOLE_DOCKER_TAG=2022.09.1
      - S6_OVERLAY_VERSION=v3.1.1.2
      - PIHOLE_INSTALL=/etc/.pihole/automated install/basic-install.sh
      - PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
      - PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log
      - S6_KEEP_ENV=1
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - FTLCONF_LOCAL_IPV4=0.0.0.0
      - FTL_CMD=no-daemon
      - DNSMASQ_USER=pihole
    expose:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    hostname: 2b2fa1650f17
    image: pihole/pihole:latest
    ipc: private
    labels:
      net.unraid.docker.icon: https://i.imgur.com/OWkNcEn.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:80]/admin
      org.opencontainers.image.created: '2022-09-02T21:33:03.014Z'
      org.opencontainers.image.description: Pi-hole in a docker container
      org.opencontainers.image.licenses: ""
      org.opencontainers.image.revision: 0d5a001916335cf4b27408217063ac9e04cc7e0d
      org.opencontainers.image.source: https://github.com/pi-hole/docker-pi-hole
      org.opencontainers.image.title: docker-pi-hole
      org.opencontainers.image.url: https://github.com/pi-hole/docker-pi-hole
      org.opencontainers.image.version: 2022.09.1
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
    networks:
      - br0
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/pihole/pihole:/etc/pihole
      - /mnt/user/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
networks:
  br0:
    external: true
    name: br0
