version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

x-env-tz: &env-tz
  TZ: $TZ
x-env-common: &env-common
  PUID: $PUID
  PGID: $PGID

x-common: &common
  networks:
    - default
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped #no, always

services:
  overseerr:
    <<: *common
    container_name: overseerr
    image: sctx/overseerr:latest
    environment:
      <<: *env-tz
    ports:
      - 33200:5055/tcp
    volumes:
      - $DOCKERDIR/appdata/overseerr:/app/config:rw