version: "3"

services:
  tailscale:
      container_name: tailscale
      image: tailscale/tailscale:latest
      restart: unless-stopped
      volumes:
        - "/opt/tailscale/var_lib:/var/lib"
        - "/dev/net/tun:/dev/net/tun"
      hostname: ASDASDASDASD
      environment:
        - TZ=America/New_York
      privileged: true
      network_mode: host
      cap_add:
        - net_admin
        - sys_module
      command: tailscaled
