version: "3"

networks:
  default:
    external: true
    name: custom-bridge
volumes:
  grafana-data:

services:
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    container_name: grafana
    ports:
      - 33001:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - default
    user: '104'
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3