version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /opt/komga/config:/config
      - /mnt/media/books:/mnt/media/books
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 25600:25600
    user: "0:0"
    restart: unless-stopped