version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /opt/komga/config
        target: /config
      - type: bind
        source: /mnt/media/books
        target: /mnt/media/books
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 25600:25600
    user: "0:0"
    restart: unless-stopped