version: '2'

networks:
  default:
    name: custom-bridge
    driver: bridge

services:
  lancache-dns:
    container_name: lancache-dns
    image: lancachenet/lancache-dns:latest
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
  monolithic:
    container_name: monolithic
    image: lancachenet/monolithic:latest
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    ports:
      - 49480:80/tcp
      - 49443:443/tcp
    volumes:
      - /mnt/nas-media/games/Steam:/data/cache
      - /opt/lancache:/data/logs
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3