version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=trueblack
      - TP_COMMUNITY_THEME=true
    ports:
     - 26300:8686/tcp
    volumes:
      - $MEDIADIR/music:/mnt/media/music:rw,slave
      - $APPDATA/lidarr:/config
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:8686 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 2