services:
  mailrise:
    image: yoryan/mailrise
    container_name: mailrise
    ports:
      - 8025:8025
    restart: unless-stopped
    volumes:
      - /opt/stacks/mailrise/mailrise.conf:/etc/mailrise.conf
      - ./letsencrypt:/etc/letsencrypt
networks: {}
