version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

services:
  mylar:
    container_name: mylar
    image: ghcr.io/linuxserver/mylar
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:mylar
      - TP_THEME=trueblack
      - TP_COMMUNITY_THEME=true
    ports:
     - 26402:8090/tcp
    volumes:
      - $MEDIADIR/comics:/mnt/media/comics:rw,slave
      - $APPDATA/mylar:/config
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:8090 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 2