# https://github.com/nextcloud/all-in-one/blob/main/compose.yaml

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    network_mode: "host"
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80 # Can be removed when running behind a web server or reverse proxy
      - 8080:8080
      - 8443:8443 # Can be removed when running behind a web server or reverse proxy
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 10.10.55.98
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6
      # COLLABORA_SECCOMP_DISABLED: false
      # NEXTCLOUD_DATADIR: /mnt/ncdata
      # NEXTCLOUD_MOUNT: /mnt/
      # NEXTCLOUD_UPLOAD_LIMIT: 10G
      # NEXTCLOUD_MAX_TIME: 3600
      # NEXTCLOUD_MEMORY_LIMIT: 512M
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts
      # NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes
      # NEXTCLOUD_ADDITIONAL_APKS: imagemagick
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick
      # NEXTCLOUD_KEEP_DISABLED_APPS: false 

volumes:
  # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

networks: {}