---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/stacks/nextcloud/config:/config
      - /opt/stacks/nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped