services:
  overseerr:
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PORT=5055
    image: sctx/overseerr
    restart: unless-stopped
    ports:
      - 5055:5055/tcp
    volumes:
      - /opt/stacks/overseerr/config:/app/config