version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

services:
  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - UID=$PUID
      - GID=$PGID
    ports:
      - 26901:5055/tcp
    volumes:
      - $APPDATA/overseerr:/config
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055 || exit 1
      interval: 60s
      timeout: 10s
      retries: 2
    dns:
      - 1.1.1.1
      - 1.0.0.1