version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: $TZ
      WEBPASSWORD: $WEBPASSWORD
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 33480:80/tcp
    volumes:
      - $APPDATA/pihole/etc-pihole:/etc/pihole
      - $APPDATA/pihole/etc-dnsmasq.d:/etc/dnsmasq.d