version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

services:
  plexripper:
    container_name: plexripper
    image: plexripper/plexripper
    restart: unless-stopped
    environment:
      - TZ=$TZ
    ports:
      - 7000:7000/tcp
    volumes:
      - $MEDIADIR/movies:/mnt/media/movies:rw,slave
      - $MEDIADIR/music:/mnt/media/music:rw,slave
      - $MEDIADIR/tv:/mnt/media/tv:rw,slave
    security_opt:
      - no-new-privileges:true
#    healthcheck: #no wget or curl
#      test: wget --no-verbose --tries=1 --spider http://localhost:7000 || exit 1
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
    build:
      context: .
      dockerfile: ./Dockerfile