version: "2.1"
networks:
  default:
    external: true
    name: custom-bridge
services:
  pmm:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: pmm
    environment:
      - TZ=$TZ
      - UID=$PUID
      - GID=$PGID
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - $APPDATA/pmm:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true