version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

x-environment: &default-environment
  environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID
    - DOCKER_MODS=ghcr.io/gilbn/theme.park:readarr
    - TP_THEME=trueblack
    - TP_COMMUNITY_THEME=true

x-settings: &settings
  image: lscr.io/linuxserver/readarr:develop
  restart: unless-stopped  
  security_opt:
    - no-new-privileges:true
  healthcheck:
    test: "curl --fail http://localhost:8787 || exit 1"
    interval: 60s
    timeout: 10s
    retries: 2

services:
  readarrbooks:
    container_name: readarrbooks
    ports:
     - 26400:8787/tcp
    volumes:
      - $MEDIADIR/books:/mnt/media/books:rw,slave
      - $APPDATA/readarrbooks:/config
    <<: [*default-environment, *settings]
  readarraudiobooks:
    container_name: readarraudiobooks
    ports:
     - 26401:8787/tcp
    volumes:
      - $MEDIADIR/audiobooks:/mnt/media/audiobooks:rw,slave
      - $APPDATA/readarraudiobooks:/config
    <<: [*default-environment, *settings]