version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    init: true
    user: 1000:1000
    volumes:
      - /opt/recyclarr:/config:rw
    environment:
      - TZ=America/New_York