version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd
      - TP_THEME=trueblack
      - TP_COMMUNITY_THEME=true
    ports:
      - 26801:8080/tcp
    volumes:
      - $MEDIADIR:/mnt/media:rw,slave
      - $APPDATA/sabnzbd2:/config:rw
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:8080 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 2