version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

x-environment: &default-environment
  environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID
    - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
    - TP_THEME=trueblack
    - TP_COMMUNITY_THEME=true

x-settings: &settings
  image: lscr.io/linuxserver/sonarr:develop
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  healthcheck:
    test: "curl --fail http://localhost:8989 || exit 1"
    interval: 60s
    timeout: 10s
    retries: 2

services:
  sonarr1080p:
    container_name: sonarr1080p
    ports:
      - 26100:8989/tcp
    volumes:
      - $MEDIADIR/tv:/mnt/media/tv:rw,slave
      - $APPDATA/sonarr1080p:/config:rw
    <<: [*default-environment, *settings]
  sonarr4k:
    container_name: sonarr4k
    ports:
      - 26101:8989/tcp
    volumes:
      - $MEDIADIR/tv:/mnt/media/tv:rw,slave
      - $APPDATA/sonarr4k:/config:rw
    <<: [*default-environment, *settings]
  sonarranime:
    container_name: sonarranime

    ports:
      - 26102:8989/tcp
    volumes:
      - $MEDIADIR/tv:/mnt/media/tv:rw,slave
      - $APPDATA/sonarranime:/config:rw
    <<: [*default-environment, *settings]