version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /opt/tautulli:/config
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
    ports:
      - 24100:8181
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:8181 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3