version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - serverIP=10.10.50.62
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeName=docker02
    volumes:
      - $APPDATA/tdarr/server:/app/server
      - $APPDATA/tdarr/configs:/app/configs
      - $APPDATA/tdarr/logs:/app/logs
      - $MEDIADIR:/media
      - $APPDATA/tdarr_node/temp:/temp