version: "3.4"
services:
  tdarr_node:
    container_name: tdarr_node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - nodeID=$NODEID
      - serverIP=10.10.50.62
      - serverPort=8266
    volumes:
      - $APPDATA/tdarr_node/config:/app/configs
      - $APPDATA/tdarr_node/logs:/app/logs
      - $MEDIADIR:/mnt/media
      - $MEDIADIR/temp:/temp
#    devices:
#      - /dev/dri:/dev/dri
