version: '3.3'
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - 3001:3001
    volumes:
      - /opt/stacks/uptime-kuma/config:/app/data
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ['CMD', 'node', 'extra/healthcheck.js']
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 180s