version: "3"
services:
  vserver3:
    container_name: visionect-server
    image: visionect/visionect-server-v3
    privileged: true
    ulimits:
      core: 0
    depends_on:
      - visionect-server-redis
      - visionect-server-pdb
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    restart: always
    links:
      - "postgres_db:postgres"
      - "redis:redis"
    ports:
      - 8081:8081
      - 11113:11113
    environment:
      - DB2_1_PORT_5432_TCP_ADDR=postgres
      - DB2_1_PORT_5432_TCP_USER=visionect
      - DB2_1_PORT_5432_TCP_PASS=visionect
      - DB2_1_PORT_5432_TCP_DB=koala
      - REDIS_ADDRESS=redis:6379
#   volumes:
#     - /dev/shm:/dev/shm
  visionect-server-pdb:
    container_name: visionect-server-pdb
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=visionect
      - POSTGRES_DB=koala
      - POSTGRES_PASSWORD=visionect
      - PGPASSWORD=visionect
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  visionect-server-redis:
    image: redis
    restart: always