version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
  monolithic:
    image: lancachenet/monolithic:latest
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /mnt/nas-media/games/Steam:/data/cache
      - /opt/lancache:/data/logs