version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  9999:
    container_name: 
    image: 
    restart: unless-stopped
    ports:
      - 33100:80/tcp
    volumes:
      - /opt/9999:/9999:rw
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - NODE_ENV=production