version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

x-common: &common
  networks:
    - default
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped #no, always

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    << : *common
    environment:
      - TZ=${TZ}
      - UID=${PUID}
      - GID=${PGID}
      - NODE_ENV=production
    ports:
      - 33100:80/tcp
    volumes:
      - $APPDATA/dashy:/app/public:rw
    healthcheck:
      test: "curl --fail http://localhost:80 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3