version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    ports:
      - 33100:80/tcp
    volumes:
      - /opt/dashy/conf.yml:/app/public/conf.yml:rw
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - NODE_ENV=production