version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge
    driver: bridge

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
      - "TZ=America/New_York"
    restart: unless-stopped #no, always
    ports:
      - 61208:61208/tcp
      - 61209:61209/tcp
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:61208 || exit 1
      interval: 1m0s
      timeout: 10s
      retries: 3