version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

x-common: &common
  networks:
    - default
  restart: unless-stopped #no, always

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    pid: host
    << : *common
    environment:
      - TZ: ${TZ}
      - GLANCES_OPT: -w
    ports:
      - 61208:61208/tcp
      - 61209:61209/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock