version: "3"

networks:
  default:
    external: true
    name: custom-bridge
volumes:
  grafana-data:
services:
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    container_name: grafana
    ports:
      - 33001:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - default
    user: '104'