version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

x-common: &common
  networks:
    - default
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped #no, always

services:
  komga:
    container_name: komga
    image: gotson/komga
    user: ${PUID}:${PGID}
    << : *common
    environment:
      - TZ=${TZ}
    ports:
      - 28100:8080/tcp
    volumes:
      - $MEDIADIR/comics/:/comics:rw,slave
      - $MEDIADIR/books/:/books:rw,slave
      - $APPDATA/komga:/config:rw
    healthcheck:
      test: "curl --fail http://localhost:8080 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3