version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

services:
  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    networks:
      - default
    dns:
      - 1.1.1.1
      - 1.0.0.1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=trueblack
      - TP_COMMUNITY_THEME=true
    ports:
      - 33200:5055/tcp
    volumes:
      - /opt/overseerr:/app/config:rw
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
