version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

x-common: &common
  networks:
    - default
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped #no, always

services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    << : *common
    environment:
      - TZ: $TZ
    ports:
      - 33200:5055/tcp
    volumes:
      - $APPDATA/overseerr:/app/config:rw