version: "3.9"

networks:
  default:
    name: custom-bridge
    driver: bridge

services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped #no, always
    environment:
      - TZ=${TZ}
    ports:
      - 33200:5055/tcp
    volumes:
      - $APPDATA/overseerr:/app/config:rw
#    healthcheck:
#      test: "curl --fail http://localhost:5055 || exit 1"
#      interval: 1m30s
#      timeout: 10s
#      retries: 3