version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  plexripper:
    container_name: plexripper
    image: plexripper/plexripper
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7000:7000/tcp
    volumes:
      - /mnt/truenas:/media:rw,slave
    environment:
      - TZ=${TZ}
#    healthcheck:#NO-CURL-AVAILABLE
#      test: "curl --fail http://localhost:7000 || exit 1"
#      interval: 1m30s
#      timeout: 10s
#      retries: 3