version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  prom_node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: prom_node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    security_opt:
      - no-new-privileges:true