version: "3"

networks:
  default:
    external: true
    name: custom-bridge

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 29090:9090
    volumes:
      - /opt/prometheus/etc:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    environment:
      - TZ=${TZ}
    healthcheck:
      test: "curl --fail http://localhost:9090 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3