version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    ports:
      - 25100:9696/tcp
    volumes:
      - /opt/prowlarr:/config:rw
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=trueblack
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:9696 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3