version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  rancher:
    container_name: rancher
    image: rancher/rancher:stable
    restart: unless-stopped
    ports:
      - 32100:443/tcp
    volumes:
      - /opt/rancher:/var/lib/rancher
    environment:
      - TZ=America/New_York
    privileged: true
    security_opt:
      - label=disable
    healthcheck:
      test: "curl --fail https://localhost:443 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3