version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  sonarr4k:
    container_name: sonarr4k
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    ports:
      - 26101:8989/tcp
    volumes:
      - /mnt/synology/tv/4k:/media/tv/4k:rw,slave
      - /mnt/synology/downloads:/media/downloads:rw,slave
      - /opt/sonarr4k:/config:rw
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_ADDON=sonarr-4k-logo
      - TP_THEME=trueblack
      - TP_COMMUNITY_THEME=true
    healthcheck:
      test: "curl --fail http://localhost:8989 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3