version: '3.3'
services:
    checkmk:
        ports:
            - 38180:5000
        tmpfs: /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
        volumes:
            - /opt/checkmk:/omd/sites
            - /etc/localtime:/etc/localtime:ro
        container_name: checkmk
        restart: always
        image: checkmk/check-mk-free:2.1.0p18