version: "3.9"

networks:
  default:
    external: true
    name: custom-bridge

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - UID=$PUID
      - GID=$PGID
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=800
    ports:
      - 33100:80/tcp
    volumes:
      - $APPDATA/dashy/conf.yml:/app/public/conf.yml:rw
      - $APPICONS:/app/public/item-icons:ro
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 2
      start_period: 30s