version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    ports:
      - 25200:8080/tcp
    volumes:
      - /mnt/nas-downloads/usenet:/media/downloads/usenet:rw,slave
      - /opt/sabnzbd:/config:rw
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl --fail http://localhost:8080 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3